[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
watchPaths = ["services/polymarket-indexer/**"]

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
